service: vibrancy
#app: vibrancy
#org: barryf

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

functions:
  render:
    handler: handlers/render.process
    events:
      - http:
          path: /{slug+}
          method: get
  list:
    handler: handlers/list.process
    events:
      - http:
          path: /
          method: get
  webhook:
    handler: handlers/webhook.process
    events:
      - http:
          path: /webhook
          method: post
  download:
    handler: handlers/download.process
  upsert:
    handler: handlers/upsert.process

resources:
  Resources:
    posts:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: posts
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  #- serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-offline

custom:
  customDomain:
    domainName: barryf.co.uk
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
