name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test Architect project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: actions/setup-ruby@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        MEDIA_ENDPOINT_URL: http://localhost:3334/
      run: npm test
