name: Run tests

on: [push]

jobs:
  test:
    name: Test Architect project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run npm tests
      run: |
        npm install
        npm test
