name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build app
        uses: architect/action-build@v3

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Run linting
        run: npm run lint

      - name: Run tests
        env:
          MEDIA_ENDPOINT_URL: http://localhost:3333/
          ROOT_URL: http://localhost:4444/
        run: npm test
